[package]
description = "Goshen Network Tester"
name = "riscv-l2-chain-test"
version = "0.1.0"
edition = "2021"

[dependencies]
ethcore = { path = "../../crates/ethcore", default-features = true }
hash-db = { path = "../../crates/db/hash-db-0.12.4", default-features = false }
memory-db = { path = "../../crates/db/memory-db", default-features = false }
trie-db = { path = "../../crates/db/trie-db-0.12.4", default-features = false }
keccak-hasher = { path = "../../crates/util/keccak-hasher", default-features = false }
ethereum-types = { version = "0.12.1", default-features = false }
ethcore-builtin = { path = "../../crates/vm/builtin", default-features = false }
byteorder = { version = "1.3.2", default-features = false }
common-types = { path = "../../crates/ethcore/types", default-features = false }
rlp = { version = "0.5.1", default-features = false }
rustc-hex = { version = "2.1.0" }
goshen-chain={path="../../", default-features = false}

[[bin]]
name = "riscv-l2-chain-test"
path = "src/main.rs"
doc = false

[features]
default=["std"]
std=["rlp/std"]