[package]
name = "riscv-evm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buddy-alloc = "0.4.1"
cfg-if = "1.0.0"

[features]
