[package]
name = "brotli-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brotli = {path="../../crates/util/brotli",default-features = false}
common-types = { path = "../../crates/ethcore/types", default-features = false,features=["std"] }
byteorder = { version = "1.3.2", default-features = false}
rlp = { version = "0.5.1", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }

[[bin]]
name="brotli-bin"
path = "src/main.rs"
doc = false

