name:                           Check

on:
  pull_request:
  push:
    branches:
      - main
      - dev
jobs:
  check:
    name:                       Check
    runs-on:                    ubuntu-16.04
    steps:
      - name:                   Checkout sources
        uses:                   actions/checkout@main
        with:
          submodules:           true
      - name:                   Install stable toolchain
        uses:                   actions-rs/toolchain@v1
        with:
          toolchain:            stable
          profile:              minimal
          override:             true
      - name:                   Run cargo check 1
        uses:                   actions-rs/cargo@v1
        with:
          command:              check
          args:                 --locked --no-default-features --all --verbose  --exclude riscv-l2chain